### PR TITLE
Good first css improvements

### PR DESCRIPTION
**Pull request by zeshhaan**
Proposed changes
- improve spaces aka `line-height` between texts giving breathing room for readers
- make `aside` sidebar `sticky`
- other minor enhancements
    - remove `:visited`
    - reset `ul`, `li` defaults
    - prettify `code` element

### CODE REVIEW

**Review by AngelMunoz — APPROVED** [review]
Looks great! I just checked it locally I'll merge and deploy after thanks for the improvements they do make a change.

I haven't done anything related to mobile, if you feel generous enough to give it a chance I would be really glad :)

In the mean time Thank you very very much!

**Comment by zeshhaan** [comment]
Thank you! Glad to hear that. I forgot about mobile thing, will check that out and suggest changes there too.

Side question, do you plan to add sass or tailwindcss?

**Comment by AngelMunoz** [comment]
Perla doesn't support sass currently so we can't do it yet, I guess we can add tailwind but from what I know the sole css file is quite heavy right?

In any case if you want to explore those areas I'm open for it 😁

**Comment by zeshhaan** [comment]
Sure thing! I am excited to see improvements on the home page. 

I would love to use pure CSS if then. I thought tailwind is lightweight because of purge and JIT making it faster.

**Pull request merged**
